import { test, expect } from '../../fixtures/auth.fixture';
import { ApiHelper } from '../../fixtures/api.fixture';

/**
 * E2E spec: CodecSelector inside the trunk creation wizard.
 *
 * Auth / navigation pattern mirrors trunks.spec.ts:
 *   - `platformAdminPage` fixture injects a JWT into sessionStorage (asterisk-auth),
 *     then each test navigates to the target URL.
 *   - `authenticatedApiContext` drives pre- and post-test cleanup via ApiHelper.
 *
 * Step-nav testids (prefix trunk-wizard, generated by WizardLayout with testIdPrefix="trunk-wizard"):
 *   trunk-wizard-step-<key>  — clickable step indicator
 *   trunk-wizard-next        — advance one step
 *   trunk-wizard-back        — retreat one step
 *   trunk-wizard-finish      — submit on the last step
 *
 * CodecSelector testids (testId="trunk-wizard-codecs", rendered inside the media step):
 *   trunk-wizard-codecs-add-<token>       — add button for a catalog codec
 *   trunk-wizard-codecs-selected-<token>  — selected row for a codec
 *   trunk-wizard-codecs-up-<index>        — move row up (0-based)
 *   trunk-wizard-codecs-down-<index>      — move row down (0-based)
 *   trunk-wizard-codecs-remove-<index>    — remove a row
 *
 * When the /admin/voice/codecs backend endpoint is unavailable the selector
 * falls back to the full CODEC_CATALOG with all codecs marked as installed
 * (installed === null → isInstalled = true in availableToAdd).  The curated
 * fallback codecs (ulaw, alaw, g722, …) are therefore always enabled.
 */
test.describe('Trunk wizard — CodecSelector', () => {
  test('should add codecs, reorder, and save a trunk via the wizard', async ({
    platformAdminPage: page,
    authenticatedApiContext,
  }) => {
    const api = new ApiHelper(authenticatedApiContext);
    const trunkName = `e2e-codec-wizard-${Date.now()}`;

    // ── Step 0: navigate to the trunk wizard ────────────────────────────────
    await page.goto('/admin/trunks');
    await expect(page.getByTestId('trunks-page')).toBeVisible();
    await page.getByTestId('trunks-wizard-btn').click();
    await expect(page.getByTestId('trunk-wizard-layout')).toBeVisible();

    // ── Step 1: Provider — pick "generic" (IP-ACL, available without backend) ─
    await expect(page.getByTestId('trunk-wizard-step-provider')).toBeVisible();
    await page.getByTestId('trunk-wizard-provider-generic').click();
    await page.getByTestId('trunk-wizard-next').click();

    // ── Step 2: Connection — fill required fields ────────────────────────────
    await expect(page.getByTestId('trunk-wizard-step-connection')).toHaveAttribute(
      'aria-current',
      'step',
    );
    await page.getByTestId('trunk-wizard-name').fill(trunkName);
    await page.getByTestId('trunk-wizard-maxChannels').clear();
    await page.getByTestId('trunk-wizard-maxChannels').fill('5');
    // Generic provider defaults to ip-acl; fill matchHost (required for validation).
    await page.getByTestId('trunk-wizard-matchHost').fill('203.0.113.1');
    await page.getByTestId('trunk-wizard-next').click();

    // ── Step 3: Media — expand the advanced section, then use CodecSelector ──
    await expect(page.getByTestId('trunk-wizard-step-media')).toHaveAttribute(
      'aria-current',
      'step',
    );
    // The media step starts collapsed; toggle it open.
    await page.getByTestId('trunk-wizard-media-toggle').click();
    await expect(page.getByTestId('trunk-wizard-media-section')).toBeVisible();

    // The codec container should be present.
    await expect(page.getByTestId('trunk-wizard-codecs')).toBeVisible();

    // Add ulaw first.
    await page.getByTestId('trunk-wizard-codecs-add-ulaw').click();
    await expect(page.getByTestId('trunk-wizard-codecs-selected-ulaw')).toBeVisible();

    // Add g722 second.
    await page.getByTestId('trunk-wizard-codecs-add-g722').click();
    await expect(page.getByTestId('trunk-wizard-codecs-selected-g722')).toBeVisible();

    // Both selected rows are visible.  ulaw is at index 0, g722 at index 1.

    // Reorder: click down-0 to demote ulaw (move it from position 0 to position 1).
    await page.getByTestId('trunk-wizard-codecs-down-0').click();

    // After the move g722 is now at index 0 and ulaw at index 1.
    // Assert both codecs are still present (the rows remain visible).
    await expect(page.getByTestId('trunk-wizard-codecs-selected-ulaw')).toBeVisible();
    await expect(page.getByTestId('trunk-wizard-codecs-selected-g722')).toBeVisible();

    // Assert the new order directly: the first selected row must now be g722.
    await expect(
      page.locator('[data-testid^="trunk-wizard-codecs-selected-"]').first(),
    ).toHaveAttribute('data-testid', 'trunk-wizard-codecs-selected-g722');

    // Supplementary: check button disabled state (g722 is at the top, so up-0 is disabled).
    await expect(page.getByTestId('trunk-wizard-codecs-up-0')).toBeDisabled();
    await expect(page.getByTestId('trunk-wizard-codecs-down-0')).toBeEnabled();

    // Advance to step 4 (outbound route).
    await page.getByTestId('trunk-wizard-next').click();

    // ── Step 4: Outbound — disable the optional route to skip it ─────────────
    await expect(page.getByTestId('trunk-wizard-step-outbound')).toHaveAttribute(
      'aria-current',
      'step',
    );
    // Turn off "add outbound route" so we don't need to fill a real pattern.
    const addRouteSwitch = page.getByTestId('trunk-wizard-addOutboundRoute');
    const isChecked = await addRouteSwitch.isChecked();
    if (isChecked) {
      await addRouteSwitch.click();
    }
    await expect(page.getByTestId('trunk-wizard-outbound-warning')).toBeVisible();
    await page.getByTestId('trunk-wizard-next').click();

    // ── Step 5: Inbound DID — disable to skip ────────────────────────────────
    await expect(page.getByTestId('trunk-wizard-step-inbound')).toHaveAttribute(
      'aria-current',
      'step',
    );
    const addDidSwitch = page.getByTestId('trunk-wizard-addDid');
    const isDidChecked = await addDidSwitch.isChecked();
    if (isDidChecked) {
      await addDidSwitch.click();
    }
    await expect(page.getByTestId('trunk-wizard-inbound-warning')).toBeVisible();
    await page.getByTestId('trunk-wizard-next').click();

    // ── Step 6: Review & finish ───────────────────────────────────────────────
    await expect(page.getByTestId('trunk-wizard-step-review')).toHaveAttribute(
      'aria-current',
      'step',
    );
    await expect(page.getByTestId('trunk-wizard-review-step')).toBeVisible();

    // Submit the wizard.
    await page.getByTestId('trunk-wizard-finish').click();

    // After creation the wizard navigates back to /admin/trunks.
    await expect(page).toHaveURL(/\/admin\/trunks/);
    // Guard: wait for the React tree to mount before interacting with the page.
    await expect(page.getByTestId('trunks-page')).toBeVisible();

    // Search by the unique name to confirm the trunk appears in the list.
    await page.getByTestId('trunks-search').fill(trunkName);
    await expect(page.getByText(trunkName)).toBeVisible();

    // ── Cleanup: delete the trunk via API ─────────────────────────────────────
    const trunks = await api.listTrunks();
    const list = Array.isArray(trunks) ? trunks : (trunks.items ?? []);
    const created = list.find((t: { name: string }) => t.name === trunkName);
    if (created) await api.deleteTrunk(created.id);
  });
});
